### ISSUE TITLE
Colors of sections in left outline are not uniform

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-docs-sphinx-theme#41] opened 2020-12-14 16:17 UTC
After PR #37, the colors of sections in our left outline have different shades of gray:

![Selección_065](https://user-images.githubusercontent.com/365293/102105503-7e4e1a00-3dfd-11eb-9d62-4c0a793de687.png)

That looks really odd and something we should definitely try to fix.

However, I'm ok with leaving the lighter gray for the elements above the outline (i.e. `VERSION` and `Search`), so they don't drag too much attention to them.

@CAM-Gerlach, please take care of this one.

**Comment by CAM-Gerlach** [comment] 2020-12-14 18:20
Okay, thanks for the reminder. I'll go ahead with a PR shortly, which will harmonize the text and sidebars to the standard `#333333` used on our website, navbar and footer, and make the hover color `#000000` so its more visible. I won't modify the light gray for the search bar an version dropdown, etc;. I don't disagree with the aesthetic argument, but I also don't want to harm accessibility for those with vision impairments as @isabela-pf has reminded us. However, that can be addressed in a separate PR as this one doesn't change the status quo with that.

> After PR #37, the colors of sections in our left outline have different shades of gray:

As mentioned previously and my testing confirms, this was not caused by that PR and has been the case as long as the theme has been used for our docs; it was made much less prominent in PR #8 after I pointed out the substantial differences in the rendering of dropdown and non-dropdown elements in the menu, but none of us noticed the subtle color difference that still remained (which you can see in that screenshot) until now.

To publicly document what we previously discussed:

<details>

@CAM-Gerlach said

> Its presumably been there ever since the beginning, when the theme had a bunch of styles that were different between sections with subsections and those without, and Daniel harmonized them [PR #8] but we must have missed that one since its pretty subtle. I don't mind it terribly much since it emphasizes parent sections a little more, but which arguably could make sense, but I agree ideally they should match (and the existing color is kind of light and hard to read).

> Honestly the text colors are kind of a mess—just in terms of the left, right and top bars, some stuff uses our docs theme's `#212121` body color, some uses the base theme's `RGB(0, 0, 0, 0.65)` (about `#606060`), some uses `#77757A`, and some uses the Spyder website's `#333333`, with no apparent reason for so many similar grays and for what gets what. We really should just harmonize all of them to use `#333333` so our  color palette is cohesive and easier to read, in the direction Isabella has been recommending.

> The darker one isn't what's used for hover; hover is yet _another_ different gray, `RGB(0, 0, 0, 0.85)` (about `#262626`), which is still a fraction _lighter_ than our nominal body color. If we use `#333333` for text and `#000000` for hover, it will have exactly the same relative difference (0.20) as what you're proposing, `RGB(0, 0, 0, 0.65)` for text and `RGB(0, 0, 0, 0.85)` for hover, but be simpler, easier to read and more cohesive with the rest of the site. The current page is colored Spyder red, not gray, in addition to the red bar next to it, so it would have no effect on that.

</details>

**Comment by CAM-Gerlach** [comment] 2020-12-14 19:43
(For what its worth, the search box in fact uses _still another_ different gray color, `#6c757d`)

**Comment by isabela-pf** [comment] 2020-12-14 21:56
Thanks for thinking of accessibility! The current lighter gray for the search box and drop down outline `#6c757d` does have enough contrast on the white background, so it can stay if wanted. My goal is to unify the color palette to avoid random colors like all these, but if this color is one we want to add and carry it throughout the docs I'm fine with this kind of middle gray.

**Comment by ccordoba12** [comment] 2020-12-15 01:01
Thanks @isabela-pf for chiming in! Since you consider `#6c757d` has enough contrast, I'm going to merge the PR that fixes this issue.

**Closed as completed** 2020-12-15 01:01 UTC
Labels: enhancement

**Comment by CAM-Gerlach** [comment] 2020-12-15 04:04
Thanks @isabela-pf , much appreciated. With that PR, I actually ended up harmonizing all the greys to just two, `#606060` as middle gray (which is slightly darker/higher contrast than the existing right sidebar and search colors) and `#333333` for dark gray (as used on our website), plus black (`#000000`), so hopefully both the consistency and contrast issues should be mostly resolved now, at least as far as the grays are concerned.
